
#import "FirstViewController.h"
#import "SecondViewController.h"
#import "Dog.h"
#import "DogCell.h"

@interface FirstViewController ()

@end

@implementation FirstViewController

- (void)viewDidLoad {
    [super viewDidLoad];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
}


- (void)viewWillAppear:(BOOL) animated {
    [super viewWillAppear:animated];
    
    self.dogs = [[NSMutableArray alloc] init];
    
    Dog* dog = [[Dog alloc] init];
    dog.breed = @"CUNE'S Iron Kid";
    dog.desc = @"Know offspring: ABLIZIN'S DONA (ZORAN'S INKA) 2xW POR BANE POP'S LINNDA BENJO'S(KUBIK'S) TESA BLAGOJE'S MERI BLAGOJEVIC' DEYZI BLAGOJEVIC'S SHIVA BRAJIĆ'S (MIKIĆ'S) KIM BROTHER'S BIG BOSS BROTHER'S NICO 2xW CUKINA'S EMA CUNE'S FAJER CUNE'S IRON IRA DARIN'S LIKI DARIN'S STARA DER'S TINA DRAGAN'S KID-19 FYRIO GADFADE'S TOMI GARLAUNIS' DARK FACE GARLAUNIS' KID II GNJATA'S PUMA GOJKO'S ZEBO 1xW HAC'S HAC ISTVAN'S GINA 2xW JAKAB'S EMA KARABINAC'S ARON KAROLY'S IRON WHISKEY KID 39 KRSTA'S (SOLE'S) BLACK JACK CH 3xW 1xD LIPCSEI IRON BAXY LJUBA'S TEA 1xL LJUBAN'S BILLY KID 2xW 1xD 2xLG LJUBAN'S DON 2xW 1xL LJUBAN'S IRON IRA 2xW 1xLG MAD COMPANY'S CSINI 1xW MALA MIRZA'S KIMI MITKO'S JANI ( AKA BLACK JUMBO) NENAD'S RINGO NERA NEZNAM'S BOGANT 2xW NOVOSEL'S BLACK JACK NOVOSEL'S GITA OTTO'S DOSER P.H'S GORO PRONAI'S ADOLF RISTIVOJEVIC'S EMA RISTIVOJEVIC'S KID 13 RISTOVOJEVIC'S PUMA RITTER'S INKA 1xD ROM ROBY'S (DRAGAN'S) EMA SAVICH'S (GULIAKOV'S BLACK KING)(CUNE'S GADZA) IRON KID CH 7xW 1xLG ROM SAVICH'S IRON KID (GULIAKOV'S BLACK KING) (CUNE'SGADZA) CH 7xW 1xLG ROM SIMON'S BABY SOLO'S (BROTHER'S) MAD MAX CH 3xW SVABA'S ZEMUN TEA SZEKA'S IRON TONY T.K.B.'S LOLA 1xW TEBOLY'S OLAH TÉBOLY'S PIGI VICTOR'S BROWN TEXALOON VIKTORIA'S NELLY VLADO'S RAMBO CH VUJOVIC'S BILLI 2xW 1xL POR WRESTLING BULL'S MARY YÁGÓ ZELENOVIC'S COBRA ROM ZELJKOVIC'S GERI ZORAN'S DZENI POR ZORAN'S INKA";
   
    dog.otac = @"Sire: DRAGON FAMILY'S RINGO (VAN HERPEN ACE)  CH 3xW 2xL";
    dog.majka = @"Dam: GARLAUNIS' SUSY  POR";
    dog.titula = @"Titles:	1xW 1xLG ROM";
    dog.tezina = @"Chain Weight:18.6 kg (41.01 pound)";
    dog.slika = @"Dog";
   
    [self.dogs addObject:dog];
    
    dog = [[Dog alloc] init];
    dog.breed = @"VOLCHIHA'S & CUNE'S MR. ZORG";
    dog.desc = @"Know offspring:.BREEDING IN SERBIA(GR CH ZORG X DONA 2W) 10. BREEDING IN SERBIA(GR CH ZORG X BLACKSTONE) 11. BREEDING IN SERBIA(GR CH ZORG X ENCA) 12. BREEDING IN SERBIA (GR CH ZORG X MIURA) 13. BREEDING IN SERBIA (GR CH ZORG X ANGIE) 14.BREEDING IN SERBIA(GR CH ZORG X VIDRA) 15. BREEDING IN SERBIS (GR CH ZORG X CH KAJA) 16. BREEDING IN SERBI(GR CH ZORG X GURZA 1XW) 17.BREEDING IN SERBIA (GRCH ZORG X INKA) 18.BREEDING IN SERBIA (GR CH ZORG X LOLITA) 19.BREEDING IN SERBIA (GR CH ZORG X LIJA) 2. BREEDING IN SERBIA( GR CH ZORG X MAZA 1XW) 20.BREEDING IN SERBIA (GR CH ZORG X TRISH) 21. BREEDING IN SERBIA (GRCH ZORG X NORA) 22. BREEDING IN SERBIA - REPEATED BREEDING 10 23.BREEDING IN SERBIA 24 BREEDING IN SERBIA 24.BREEDING IN SERBIA 3. BREEDING IN SERBIA (GR CH ZORG X CH BELA) 4. BREEDING IN SERBIA (GR CH ZORG X ZORKA) 5. BREEDING IN SERBIA (GR CH ZORG X CH ZIKA III) 6. BREEDING IN SERBIA (GR CH ZORG X ASHANTI) 7. BREEDING IN SERBIA (GR CH ZORG X BAD ROSE) 8. BREEDING IN SERBIA(GR CH ZORG X TEA) 9. BREEDING IN SERBIA (GRCH ZORG X INKA) 999 - KENNEL'S VOLCHIHA'S KATANA ACHILLES KNL'S SHARCKI ALBERT'S & HUNTER'S MAORI ALEKSANDER FILL AN-NS LINDA AN-NS REMI ANDREW'S (CUNE'S) IRON BLACK MARY ANDREW'S (CUNE'S) IRON GURZA JR ANDREY CHER'S IRON BUSYA ANDREY CHER'S IRON BUTCH APPK MALAYSIA'S (CUNE'S) TEQUILA ARNES'S ( CUNE'S) IRON GRO BECANOVIC'S IRON ZILA BIG BOYS' (CUNE'S) IRON LUCA BRASI BIMBO'S HEADSHOT BOJANIC AR FEDOR BOJANIĆ AR & MIKI FRIDA BORJA (CUNE'S) IRON COTTO BOSS UP KENNEL (CUNE'S) IRON ZENA BREEDING DONE.... BREEDING IN CUNE'S & NASTY MAN'S BREEDING IN SERBIA BREEDING IN SERBIA BREEDING IN SERBIA BREEDING IN SERBIA (GR CH ZORG X BAKTRA) BREEDING IN SERBIA(GR CH ZORG X CECA) BREEDING IN SERBIA: GR CH MR. ZORG X IRON VANDA C.C.'S & SICILIA'S BREEDING 13 C.C.'S 8 C.C.'S BLACK LILI C.C.'S BREEDING 11 CHRIS' (CUNE'S) IRON MAMBA CODY'S ZEN CRAZY'S IRON VETRA CRISTI'S DELIA CUNE AND BOJANIĆ BREEDING 2016 CUNE' REPEATED BREEDING CUNE'S & N.N.K'S BREEDING 2016 CUNE'S & VOLCHIHA'S LITTLE IRON KID 1xW 1xLG B.I.S CUNE'S (M.M KENNEL'S) IRON ZORA CUNE'S (VOLCHIHA'S) VEGA CUNE'S BREEDING CUNE'S BREEDING CUNE'S BREEDING CUNE'S BREEDING START CUNE'S IRON KIDA D.ROB'S ( CUNE'S ) IRON SHOGUN DEMENTEV'S ZLYUKA DENI'S (CUNE'S) IRON MADDOX EAGLE'S(AN-NS'S) BINGO G KENNEL'S VUK GR CH MR.ZORG X BIG MAMMA PUPS 2014 GR CH MR.ZORG X CHANA II PUPPIES 2014 GR CH MR.ZORG X LOTA DOUBLE BREEDING 2014 HUNTER KENNEL'S MAORI J.L. SOUL'S KENNEL (NASTYMAN) CHESTERFIELD GT JOHNSON'S (CUNE'S) IRON BOY K.I.M KENNELS (DAWAHER) IRON BEE GT KARANVER'S(CUNE'S) IRON TAJ KEMRAN'S (ACHILLES KNL'S) ZULUS KK'S ASSO KK'S IRA KK'S JEEP KOCZO'S (C.C'S) ARGOS KOSA'S (CUNE'S) IRON INTERSTELLAR LEGION KENNEL'S MUFASA LEGION KENNEL'S MUSASHI LEGION KENNELS PEANUT M.M. KENNEL'S SANTO MARIN'S&CUNE'S BREEDING MISKE (ZUBA) LUJKA MKU'S (CUNE'S) IRON BAKAL NORTH SIDE KENNEL'S (CUNE'S) IRON LEO NORTHERN LIGHT'S KYLIE OIRAT IRON MORENA OIRAT'S MORENNA OLD BANDIT'S BLOOD PANTHER OWENS' (CUNE'S) KILLER PAUL'S IRON ZIKA  PAUL'S IRON CUBA! PINTACUDA'S(AN-NS'S) LUCKY PITBURG'S SANTANA PJK'S BIBBI PJK'S NITRO PJK'S(STRIC RUMA'S) MOLLY PLAN BREEDING POJKE'S CALI PONOVLJENO PARENJE PONOVLJENO PARENJE RIB KENNEL (CUNE'S) IRON BUDDHA RIB KENNEL (M.M KENNEL) IRON ZORKA JR RNB'S BLACK KING RS KENNEL (CUNE'S) IRON ARKAN S&S TEAM'S DJANGA S' (CUNE'S & VOLCHIHA'S) ORO FERRO INKA SERGEY'S MICHIGAN 1xLG ( G.I.S ) SIN FRONTERA'S RAIAH SINISA PAVLIC'S (CUNE'S) IRON SPOT SOKUROW'S (XARON'S) (ACHILLES KNL'S) PUMA SOVIETIC'S RADA STEEL DOG'S(CUNE'S) TRAMONTANA STEELDOG TEAM'S BLACK JUZA STEELDOG TEAM'S BREEDING STEELDOG TEAM'S ODINO STEELDOG TEAM'S VALCHIRIA STEVEN'S IRON JOEL STRIC RUMA & BOJANIC KORONA STRIC RUMA & BOJANIC SALVADOR STRIC RUMA'S & BOJANIC'S CECA JR TATI'S (CUNE'S) IRON CANDY TEMO'S MIRKO CRO COP TY'S (CUNE'S) MR. ZORG JR. URAL KNL'S GROM V.R.K CASSANDRAK'S BLACK HEADED VARNA'S(STRIC RUMA'S) ZORGA VOLCHIHA KNL DGANGA VOLCHIHA KNL KATRIN VOLCHIHA KNL RONDA VOLCHIHA KNL'S KOVAL VOLCHIHA'S ANGOLA 2xW VOLCHIHA'S ARTHUR VOLCHIHA'S BRIDING VOLCHIHA'S BRIDING2013 VOLCHIHA'S CH MR. ZORG X LOTA 2013 VOLCHIHA'S GORINICH VOLCHIHA'S GRO 2xW G.I.S VOLCHIHA'S KATANA VOLCHIHA'S KATRIN VOLCHIHA'S LINDA VOLCHIHA'S NEW BREEDENG VOLCHIHA'S NITRO VOLCHIHA'S OPTIMUS 1xL VOLCHIHA'S PLANNED BREEDING VOLCHIHA'S PLANNED BREEDING 2 VOLCHIHA'S SANTIAGO JR VOLCHIHA'S TCUNAMI VOLCHIHA'S ZOOLA VON-CORO'S BLACK KLEA VON-CORO'S BLACK SHREDDER WILCOX' (CUNE') IRON BULL ZORBA KENNEL'S IRON BLACK PIRANHA ZUBA'S POGANI 1 LG GT";
    dog.otac = @"Sire: VOLCHIHA'S SANTIAGO  (Ex GR) CH 5xW 1xLG D.O.Y POR";
    dog.majka = @"Dam: HARD-LINE'S (VOLCHIHA'S) NJAPA  POR";
    dog.titula = @"Titles:GR CH 5xW B.I.S & D.O.Y";
    dog.tezina = @"Chain Weight:18.6 kg (41.01 pound)";
    dog.slika = @"cunejunior-1";
    
    [self.dogs addObject:dog];
    
    dog = [[Dog alloc] init];
    dog.breed = @"Buki iron line";
    dog.desc = @"Izvanredan pas";
    dog.otac = @"Mupi";
    dog.majka = @"Lana";
    dog.titula = @"Grand shampion";
    dog.tezina = @"Chain Weight:18.6 kg (41.01 pound)";
    dog.slika = @"Dog";
    
    [self.dogs addObject:dog];
    
    
    self.table.delegate = self;
    self. table.self;
    [self. table reloadData];
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return [self.dogs count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    
    DogCell *cell = ((DogCell *)[tableView dequeueReusableCellWithIdentifier:@"dogCell"]);
    
    cell.breed.text = ((Dog*)[self.dogs objectAtIndex:indexPath.row]).breed;
    
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    
    SecondViewController *secondVC = [self.storyboard instantiateViewControllerWithIdentifier:
                                      @"SecondViewController"];
    
    secondVC.dog = [self.dogs objectAtIndex:indexPath.row];
    
    
    [self presentViewController:secondVC animated:YES completion:nil];
    
}



@end
